# Analyzing NYC's 311 Street Flooding Complaints from 2010 to 2020
## An Interactive Notebook Provided By MyBinder

Mark Bauer

# Goal

To run this notebook interactively through your browser (note: I am using Chrome). This is provided by  [mybinder.org](https://mybinder.org/). Additionally, this notebook demonstrates how to inspect and preview our data before we begin analysis.

# Main Python Libraries
[pandas](https://pandas.pydata.org/) is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of the Python programming language.

[Seaborn](https://seaborn.pydata.org/index.html) is a Python data visualization library based on matplotlib. It provides a high-level interface for drawing attractive and informative statistical graphics.

# Datasets

## Name:  311 Service Requests from 2010 to Present  
Website: https://data.cityofnewyork.us/Social-Services/311-Service-Requests-from-2010-to-Present/erm2-nwe9

311's data dictionary can be found in the [data-raw](https://github.com/mebauer/nyc-311-street-flooding/tree/main/data-raw) folder. 

## Please note: We only analyze 311 complaints where complaint type is street flooding. I've already extracted the data and am reading it in from our data-raw folder.

![311](../images/nyc-311-screenshot.png)

Table of Contents
=================

   * [1. Importing Libraries](#1-Importing-Libraries)
       
       
   * [2. Loading Data](#2-Loading-Data)
       
       
   * [3. Data Inspection](#3-Data-Inspection)
       * [3.1 Basic Data Inspection](#31-Basic-Data-Inspection)
       * [3.2 Calculating Summary Statistics](#32-Calculating-Summary-Statistics)
       * [3.3 Identifying Null/NA Values](#33-Identifying-Null/NA-Values)
       * [3.4 Inspecting Items In Each Column](#34-Inspecting-Items-In-Each-Column)
   
          
   * [4. Conclusion](#4-Conclusion)

# 1. Importing Libraries

In [198]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.rcParams['savefig.facecolor'] = 'white'
%matplotlib inline

Printing versions of Python modules and packages with **watermark** - the IPython magic extension.

In [199]:
%load_ext watermark

The watermark extension is already loaded. To reload it, use:
  %reload_ext watermark

In [200]:
%watermark -v -p numpy,pandas,seaborn,matplotlib

CPython 3.7.1
IPython 7.20.0

numpy 1.19.2
pandas 1.2.1
seaborn 0.11.1
matplotlib 3.3.2

Documention for installing watermark: https://github.com/rasbt/watermark

# 2. Loading Data

In [201]:
# list items in data folder
%ls ../data-raw/

311_SR_Data_Dictionary_2018.xlsx  nynta_metadata.pdf
Centerline.pdf                    raw-street-flooding-data.csv
nybb_metadata.pdf                 raw-streets-clipped.json

In [202]:
# read data as a dataframe
flooding_311 = pd.read_csv('../data-raw/raw-street-flooding-data.csv', 
                           low_memory=False)

# previewing first five rows in data
flooding_311.head()

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,incident_zip,incident_address,street_name,...,intersection_street_1,intersection_street_2,bbl,location_type,due_date,landmark,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment
0,31862075,2015-10-28T17:44:00.000,2015-10-29T11:30:00.000,DEP,Department of Environmental Protection,Sewer,Street Flooding (SJ),11694.00,BEACH 101 STREET,BEACH 101 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,25163797,2013-03-12T12:38:00.000,2013-03-12T14:20:00.000,DEP,Department of Environmental Protection,Sewer,Street Flooding (SJ),11236.00,CHURCH LANE,CHURCH LANE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,25185984,2013-03-15T12:13:00.000,2013-03-18T14:15:00.000,DEP,Department of Environmental Protection,Sewer,Street Flooding (SJ),11236.00,CHURCH LANE,CHURCH LANE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25187738,2013-03-15T12:20:00.000,2013-03-15T14:22:00.000,DEP,Department of Environmental Protection,Sewer,Street Flooding (SJ),11236.00,CHURCH LANE,CHURCH LANE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,25338491,2013-04-11T12:16:00.000,2013-04-11T12:16:00.000,DEP,Department of Environmental Protection,Sewer,Street Flooding (SJ),11236.00,CHURCH LANE,CHURCH LANE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [203]:
# previewing the last five rows of our dataframe
flooding_311.tail()

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,incident_zip,incident_address,street_name,...,intersection_street_1,intersection_street_2,bbl,location_type,due_date,landmark,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment
27863,31087754,2015-07-15T11:54:00.000,2015-07-15T13:45:00.000,DEP,Department of Environmental Protection,Sewer,Street Flooding (SJ),11225.00,99 OCEAN AVENUE,OCEAN AVENUE,...,NaN,NaN,3050240001.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27864,23268850,2012-05-21T15:13:00.000,2012-05-25T14:30:00.000,DEP,Department of Environmental Protection,Sewer,Street Flooding (SJ),10016.00,NaN,NaN,...,E 28 ST,1 AVE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27865,23298517,2012-05-25T22:41:00.000,2012-05-29T17:50:00.000,DEP,Department of Environmental Protection,Sewer,Street Flooding (SJ),10454.00,NaN,NaN,...,WILLIS AVE,E 134 ST,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27866,31195478,2015-07-30T18:05:00.000,2015-07-30T18:05:00.000,DEP,Department of Environmental Protection,Sewer,Street Flooding (SJ),11433.00,NaN,NaN,...,GUY R BREWER BOULEVARD,109 AVENUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27867,31504023,2015-09-10T08:45:00.000,2015-09-10T13:11:00.000,DEP,Department of Environmental Protection,Sewer,Street Flooding (SJ),11691.00,10-95 GIPSON STREET,GIPSON STREET,...,NaN,NaN,4157170078.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [204]:
print(flooding_311.shape)

(27868, 38)

# 3. Data Inspection

## 3.1 Basic Data Inspection

In [205]:
# the object's type
type(flooding_311)

pandas.core.frame.DataFrame

In [206]:
# printing the columns of our dataframe
flooding_311.columns

Index(['unique_key', 'created_date', 'closed_date', 'agency', 'agency_name',
       'complaint_type', 'descriptor', 'incident_zip', 'incident_address',
       'street_name', 'cross_street_1', 'cross_street_2', 'address_type',
       'city', 'facility_type', 'status', 'resolution_description',
       'resolution_action_updated_date', 'community_board', 'borough',
       'x_coordinate_state_plane', 'y_coordinate_state_plane',
       'open_data_channel_type', 'park_facility_name', 'park_borough',
       'latitude', 'longitude', 'location', 'intersection_street_1',
       'intersection_street_2', 'bbl', 'location_type', 'due_date', 'landmark',
       'bridge_highway_name', 'bridge_highway_direction', 'road_ramp',
       'bridge_highway_segment'],
      dtype='object')

In [207]:
# printing the data types of our columns
flooding_311.dtypes

unique_key                          int64
created_date                       object
closed_date                        object
agency                             object
agency_name                        object
complaint_type                     object
descriptor                         object
incident_zip                      float64
incident_address                   object
street_name                        object
cross_street_1                     object
cross_street_2                     object
address_type                       object
city                               object
facility_type                     float64
status                             object
resolution_description             object
resolution_action_updated_date     object
community_board                    object
borough                            object
x_coordinate_state_plane          float64
y_coordinate_state_plane          float64
open_data_channel_type             object
park_facility_name                 object
park_borough                       object
latitude                          float64
longitude                         float64
location                           object
intersection_street_1              object
intersection_street_2              object
bbl                               float64
location_type                     float64
due_date                           object
landmark                          float64
bridge_highway_name               float64
bridge_highway_direction          float64
road_ramp                         float64
bridge_highway_segment            float64
dtype: object

In [208]:
# printing the column names, non-null counts, and data types of our columns
flooding_311.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27868 entries, 0 to 27867
Data columns (total 38 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   unique_key                      27868 non-null  int64
 1   created_date                    27868 non-null  object
 2   closed_date                     27866 non-null  object
 3   agency                          27868 non-null  object
 4   agency_name                     27868 non-null  object
 5   complaint_type                  27868 non-null  object
 6   descriptor                      27868 non-null  object
 7   incident_zip                    27011 non-null  float64
 8   incident_address                17835 non-null  object
 9   street_name                     17835 non-null  object
 10  cross_street_1                  24114 non-null  object
 11  cross_street_2                  24103 non-null  object
 12  address_type                    27862 non-null  object
 13  city                            27012 non-null  object
 14  facility_type                   0 non-null      float64
 15  status                          27868 non-null  object
 16  resolution_description          27861 non-null  object
 17  resolution_action_updated_date  27868 non-null  object
 18  community_board                 27868 non-null  object
 19  borough                         27868 non-null  object
 20  x_coordinate_state_plane        26925 non-null  float64
 21  y_coordinate_state_plane        26925 non-null  float64
 22  open_data_channel_type          27868 non-null  object
 23  park_facility_name              27868 non-null  object
 24  park_borough                    27868 non-null  object
 25  latitude                        24426 non-null  float64
 26  longitude                       24426 non-null  float64
 27  location                        24426 non-null  object
 28  intersection_street_1           10090 non-null  object
 29  intersection_street_2           10090 non-null  object
 30  bbl                             16133 non-null  float64
 31  location_type                   0 non-null      float64
 32  due_date                        1 non-null      object
 33  landmark                        0 non-null      float64
 34  bridge_highway_name             0 non-null      float64
 35  bridge_highway_direction        0 non-null      float64
 36  road_ramp                       0 non-null      float64
 37  bridge_highway_segment          0 non-null      float64
dtypes: float64(13), int64(1), object(24)
memory usage: 8.1+ MB

In [209]:
# counts of unique values of our datatypes 
flooding_311.dtypes.value_counts()

object     24
float64    13
int64       1
dtype: int64

In [210]:
# printing index type
flooding_311.index

RangeIndex(start=0, stop=27868, step=1)

In [211]:
cols = flooding_311.columns

print('Inpecting data for unique columns (True/False)\n' + \
     ('-' * 46))

for i in cols:
    print(str(i) + ':', flooding_311[i].is_unique)

Inpecting data for unique columns (True/False)
----------------------------------------------
unique_key: True
created_date: False
closed_date: False
agency: False
agency_name: False
complaint_type: False
descriptor: False
incident_zip: False
incident_address: False
street_name: False
cross_street_1: False
cross_street_2: False
address_type: False
city: False
facility_type: False
status: False
resolution_description: False
resolution_action_updated_date: False
community_board: False
borough: False
x_coordinate_state_plane: False
y_coordinate_state_plane: False
open_data_channel_type: False
park_facility_name: False
park_borough: False
latitude: False
longitude: False
location: False
intersection_street_1: False
intersection_street_2: False
bbl: False
location_type: False
due_date: False
landmark: False
bridge_highway_name: False
bridge_highway_direction: False
road_ramp: False
bridge_highway_segment: False

In [212]:
# printing True/False if column is unique on our unique key (DOITT_ID)
flooding_311['unique_key'].is_unique

True

In [213]:
# printing descriptive statistics of our numeric columns in our data
all_columns = flooding_311.columns
flooding_311[all_columns].astype(str).describe(include='all')[:2].T.sort_values(by='unique', 
                                                                                ascending=False)

                                count unique
unique_key                      27868  27868
created_date                    27868  26359
closed_date                     27868  25392
resolution_action_updated_date  27868  25381
location                        27868  15893
longitude                       27868  15810
latitude                        27868  15808
x_coordinate_state_plane        27868  15657
y_coordinate_state_plane        27868  15614
incident_address                27868  12428
bbl                             27868  10656
cross_street_2                  27868   4687
cross_street_1                  27868   4608
street_name                     27868   4095
intersection_street_2           27868   2841
intersection_street_1           27868   2820
incident_zip                    27868    189
city                            27868     88
community_board                 27868     73
resolution_description          27868     64
park_borough                    27868      6
borough                         27868      6
open_data_channel_type          27868      5
status                          27868      4
address_type                    27868      4
due_date                        27868      2
park_facility_name              27868      1
facility_type                   27868      1
descriptor                      27868      1
complaint_type                  27868      1
agency_name                     27868      1
agency                          27868      1
location_type                   27868      1
landmark                        27868      1
bridge_highway_name             27868      1
bridge_highway_direction        27868      1
road_ramp                       27868      1
bridge_highway_segment          27868      1

In [214]:
flooding_311['descriptor'].value_counts()

Street Flooding (SJ)    27868
Name: descriptor, dtype: int64

In [215]:
flooding_311['agency'].value_counts()

DEP    27868
Name: agency, dtype: int64

In [216]:
flooding_311['agency_name'].value_counts()

Department of Environmental Protection    27868
Name: agency_name, dtype: int64

In [217]:
flooding_311['complaint_type'].value_counts()

Sewer    27868
Name: complaint_type, dtype: int64

In [218]:
flooding_311['status'].value_counts()

Closed      27862
Pending         4
Started         1
Assigned        1
Name: status, dtype: int64

In [219]:
flooding_311['resolution_description'].value_counts().reset_index().head()

                                               index  resolution_description
0  The Department of Environment Protection inspe...                   11535
1  The Department of Environmental Protection has...                    4031
2  The Department of Environmental Protection ins...                    3501
3  The Department of Environmental Protection inv...                    2914
4  The Department of Environmental Protection ins...                    1276

In [220]:
print('Top 10 Resolution Descriptions in Descending Order:\n')

for i in range(10):
    print(str(i + 1) + '.', \
          flooding_311['resolution_description'].value_counts().index[i], \
          '\nCount: ' \
          f"{flooding_311['resolution_description'].value_counts()[i]:,}" + \
          '\n')

Top 10 Resolution Descriptions in Descending Order:

1. The Department of Environment Protection inspected your complaint but could not find the problem you reported. If the condition persists, please call 311 (or 212-639-9675 if calling from a non-New York City area code) with more detailed information to submit a new complaint.
Count: 11,535

2. The Department of Environmental Protection has determined that this issue was previously reported by another customer The original complaint is being addressed. If the condition persists, please call 311 (or 212-639-9675 if calling from a non-New York City area code) to submit a new complaint.
Count: 4,031

3. The Department of Environmental Protection inspected your complaint and referred it to the Department of Transportation for further action. If the problem persists, please call 311 (or 212-639-9675 if calling from a non-New York City area code) to submit a new complaint.
Count: 3,501

4. The Department of Environmental Protection investigated this complaint and resolved the street flooding.
Count: 2,914

5. The Department of Environmental Protection inspected your complaint and cleaned the catch basin or inlet. If the condition returns, please call 311 (or 212-639-9675 if calling from a non-New York City area code) to submit a new complaint.
Count: 1,276

6. The Department of Environmental Protection has investigated this complaint and found that debris was obstructing the catch basin.
Count: 1,116

7. The status of this Service Request is currently not available online. Please call 311 for further assistance. If you are outside of New York City, please call (212) NEW-YORK (212-639-9675).
Count: 632

8. The Department of Environmental Protection has determined that this issue was previously reported by another customer The original complaint is being addressed. If the condition persists, please call 311 (or 212-639-9675 if calling from a non-New York City area code) with more detailed information to submit a new complaint.
Count: 609

9. The Department of Environmental Protection inspected your complaint and determined that the catch basin is now functioning properly. If the condition returns, please call 311 (or 212-639-9675 if calling from a non-New York City area code) to submit a new complaint.
Count: 560

10. The Department of Environmental Protection has investigated this complaint. Surcharge conditions have been confirmed, due to either a pump station malfunction, high tides, water main break, or another issue.
Count: 204

In [221]:
flooding_311.created_date.min()

'2010-01-02T08:26:00.000'

In [222]:
flooding_311.created_date.max()

'2020-12-31T15:41:00.000'

In [223]:
print('This dataset is from', \
      flooding_311.created_date.min()[0:10], \
      'to', \
      flooding_311.created_date.max()[0:10] + \
      '.')

This dataset is from 2010-01-02 to 2020-12-31.

## 3.2 Calcualting Summary Statistics

In [224]:
# display floats up to three decimals
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [225]:
# printing descriptive statistics of our numeric columns in our data
flooding_311.describe()

,unique_key,incident_zip,facility_type,x_coordinate_state_plane,y_coordinate_state_plane,latitude,longitude,bbl,location_type,landmark,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment
count,27868.00,27011.00,0.00,26925.00,26925.00,24426.00,24426.00,16133.00,0.00,0.00,0.00,0.00,0.00,0.00
mean,32415046.89,10969.30,NaN,1005503.12,186172.83,40.68,-73.92,3699596898.80,NaN,NaN,NaN,NaN,NaN,NaN
std,9176571.95,536.25,NaN,35050.06,30565.21,0.08,0.13,1075713521.34,NaN,NaN,NaN,NaN,NaN,NaN
min,15639934.00,10001.00,NaN,913357.00,121032.00,40.50,-74.25,0.00,NaN,NaN,NaN,NaN,NaN,NaN
25%,24289054.75,10312.00,NaN,986886.00,161248.00,40.61,-73.99,3060320009.00,NaN,NaN,NaN,NaN,NaN,NaN
50%,32760265.50,11220.00,NaN,1007480.00,183608.00,40.67,-73.92,4067910001.00,NaN,NaN,NaN,NaN,NaN,NaN
75%,40380993.25,11385.00,NaN,1033991.00,206464.00,40.73,-73.82,4156250046.00,NaN,NaN,NaN,NaN,NaN,NaN
max,48543132.00,11697.00,NaN,1067279.00,271876.00,40.91,-73.70,5080500078.00,NaN,NaN,NaN,NaN,NaN,NaN

In [226]:
flooding_311.describe(include=['O']).T

,count,unique,top,freq
created_date,27868,26359,2011-08-28T00:00:00.000,13
closed_date,27866,25391,2017-05-06T08:30:00.000,36
agency,27868,1,DEP,27868
agency_name,27868,1,Department of Environmental Protection,27868
complaint_type,27868,1,Sewer,27868
descriptor,27868,1,Street Flooding (SJ),27868
incident_address,17835,12427,133-25 FRANCIS LEWIS BOULEVARD,59
street_name,17835,4094,BROADWAY,116
cross_street_1,24114,4607,BEND,341
cross_street_2,24103,4686,DEAD END,492
address_type,27862,3,ADDRESS,16707
city,27012,87,BROOKLYN,6970
status,27868,4,Closed,27862
resolution_description,27861,63,The Department of Environment Protection inspe...,11535
resolution_action_updated_date,27868,25381,2017-05-06T08:30:00.000,36
community_board,27868,73,02 STATEN ISLAND,2077
borough,27868,6,QUEENS,11032
open_data_channel_type,27868,5,PHONE,16280
park_facility_name,27868,1,Unspecified,27868
park_borough,27868,6,QUEENS,11032
location,24426,15892,"{'latitude': '40.676373', 'longitude': '-73.73...",59
intersection_street_1,10090,2819,BROADWAY,98
intersection_street_2,10090,2840,BROADWAY,169
due_date,1,1,1900-01-02T00:00:00.000,1

In [227]:
# printing descriptive statistics of our numeric columns in our data
flooding_311.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
unique_key,27868.0,NaN,NaN,NaN,32415046.89,9176571.95,15639934.0,24289054.75,32760265.5,40380993.25,48543132.0
created_date,27868,26359,2011-08-28T00:00:00.000,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
closed_date,27866,25391,2017-05-06T08:30:00.000,36,NaN,NaN,NaN,NaN,NaN,NaN,NaN
agency,27868,1,DEP,27868,NaN,NaN,NaN,NaN,NaN,NaN,NaN
agency_name,27868,1,Department of Environmental Protection,27868,NaN,NaN,NaN,NaN,NaN,NaN,NaN
complaint_type,27868,1,Sewer,27868,NaN,NaN,NaN,NaN,NaN,NaN,NaN
descriptor,27868,1,Street Flooding (SJ),27868,NaN,NaN,NaN,NaN,NaN,NaN,NaN
incident_zip,27011.0,NaN,NaN,NaN,10969.3,536.25,10001.0,10312.0,11220.0,11385.0,11697.0
incident_address,17835,12427,133-25 FRANCIS LEWIS BOULEVARD,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN
street_name,17835,4094,BROADWAY,116,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cross_street_1,24114,4607,BEND,341,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cross_street_2,24103,4686,DEAD END,492,NaN,NaN,NaN,NaN,NaN,NaN,NaN
address_type,27862,3,ADDRESS,16707,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city,27012,87,BROOKLYN,6970,NaN,NaN,NaN,NaN,NaN,NaN,NaN
facility_type,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
status,27868,4,Closed,27862,NaN,NaN,NaN,NaN,NaN,NaN,NaN
resolution_description,27861,63,The Department of Environment Protection inspe...,11535,NaN,NaN,NaN,NaN,NaN,NaN,NaN
resolution_action_updated_date,27868,25381,2017-05-06T08:30:00.000,36,NaN,NaN,NaN,NaN,NaN,NaN,NaN
community_board,27868,73,02 STATEN ISLAND,2077,NaN,NaN,NaN,NaN,NaN,NaN,NaN
borough,27868,6,QUEENS,11032,NaN,NaN,NaN,NaN,NaN,NaN,NaN
x_coordinate_state_plane,26925.0,NaN,NaN,NaN,1005503.12,35050.06,913357.0,986886.0,1007480.0,1033991.0,1067279.0
y_coordinate_state_plane,26925.0,NaN,NaN,NaN,186172.83,30565.21,121032.0,161248.0,183608.0,206464.0,271876.0
open_data_channel_type,27868,5,PHONE,16280,NaN,NaN,NaN,NaN,NaN,NaN,NaN
park_facility_name,27868,1,Unspecified,27868,NaN,NaN,NaN,NaN,NaN,NaN,NaN
park_borough,27868,6,QUEENS,11032,NaN,NaN,NaN,NaN,NaN,NaN,NaN
latitude,24426.0,NaN,NaN,NaN,40.68,0.08,40.5,40.61,40.67,40.73,40.91
longitude,24426.0,NaN,NaN,NaN,-73.92,0.13,-74.25,-73.99,-73.92,-73.82,-73.7
location,24426,15892,"{'latitude': '40.676373', 'longitude': '-73.73...",59,NaN,NaN,NaN,NaN,NaN,NaN,NaN
intersection_street_1,10090,2819,BROADWAY,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN
intersection_street_2,10090,2840,BROADWAY,169,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bbl,16133.0,NaN,NaN,NaN,3699596898.8,1075713521.34,0.0,3060320009.0,4067910001.0,4156250046.0,5080500078.0
location_type,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
due_date,1,1,1900-01-02T00:00:00.000,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
landmark,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bridge_highway_name,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bridge_highway_direction,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
road_ramp,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bridge_highway_segment,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [228]:
# returning the mode of our numeric columns (excluding our unique key = 'DOITT_ID') as 'mode'
mode = flooding_311.loc[:, flooding_311.columns != 'unique_key'].mode(numeric_only=False)

# renaming index to 'mode'
mode.rename(index={0: "mode"}, inplace=True)

# transposing and printing the mode ofour numeric columns (excluding our unique key = 'DOITT_ID')
mode.T

                                                                             mode
created_date                                              2011-08-28T00:00:00.000
closed_date                                               2017-05-06T08:30:00.000
agency                                                                        DEP
agency_name                                Department of Environmental Protection
complaint_type                                                              Sewer
descriptor                                                   Street Flooding (SJ)
incident_zip                                                              10306.0
incident_address                                   133-25 FRANCIS LEWIS BOULEVARD
street_name                                                              BROADWAY
cross_street_1                                                               BEND
cross_street_2                                                           DEAD END
address_type                                                              ADDRESS
city                                                                     BROOKLYN
facility_type                                                                 NaN
status                                                                     Closed
resolution_description          The Department of Environment Protection inspe...
resolution_action_updated_date                            2017-05-06T08:30:00.000
community_board                                                  02 STATEN ISLAND
borough                                                                    QUEENS
x_coordinate_state_plane                                                1056580.0
y_coordinate_state_plane                                                 185805.0
open_data_channel_type                                                      PHONE
park_facility_name                                                    Unspecified
park_borough                                                               QUEENS
latitude                                                                    40.68
longitude                                                                  -73.74
location                        {'latitude': '40.676373', 'longitude': '-73.73...
intersection_street_1                                                    BROADWAY
intersection_street_2                                                    BROADWAY
bbl                                                                  4129700015.0
location_type                                                                 NaN
due_date                                                  1900-01-02T00:00:00.000
landmark                                                                      NaN
bridge_highway_name                                                           NaN
bridge_highway_direction                                                      NaN
road_ramp                                                                     NaN
bridge_highway_segment                                                        NaN

In [229]:
# compute pairwise correlation of columns, excluding NA/null values
flooding_311.corr()

,unique_key,incident_zip,facility_type,x_coordinate_state_plane,y_coordinate_state_plane,latitude,longitude,bbl,location_type,landmark,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment
unique_key,1.00,0.03,NaN,0.02,0.03,0.04,0.02,-0.03,NaN,NaN,NaN,NaN,NaN,NaN
incident_zip,0.03,1.00,NaN,0.71,-0.10,-0.10,0.70,0.13,NaN,NaN,NaN,NaN,NaN,NaN
facility_type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
x_coordinate_state_plane,0.02,0.71,NaN,1.00,0.46,0.46,1.00,-0.20,NaN,NaN,NaN,NaN,NaN,NaN
y_coordinate_state_plane,0.03,-0.10,NaN,0.46,1.00,1.00,0.46,-0.58,NaN,NaN,NaN,NaN,NaN,NaN
latitude,0.04,-0.10,NaN,0.46,1.00,1.00,0.46,-0.58,NaN,NaN,NaN,NaN,NaN,NaN
longitude,0.02,0.70,NaN,1.00,0.46,0.46,1.00,-0.20,NaN,NaN,NaN,NaN,NaN,NaN
bbl,-0.03,0.13,NaN,-0.20,-0.58,-0.58,-0.20,1.00,NaN,NaN,NaN,NaN,NaN,NaN
location_type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
landmark,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bridge_highway_name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bridge_highway_direction,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
road_ramp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bridge_highway_segment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
fig, ax = plt.subplots(figsize=(15,10))

sns.heatmap(flooding_311.corr(), 
            annot=True, 
            ax=ax)

In [ ]:
flooding_311.info()

In [ ]:
flooding_311.columns

In [ ]:
heatmap = flooding_311[['unique_key', 'created_date', 'closed_date', 'agency', 'agency_name',
                       'complaint_type', 'descriptor', 'incident_zip', 'incident_address',
                       'street_name', 'cross_street_1', 'cross_street_2', 'address_type',
                       'city', 'status', 'resolution_description',
                       'resolution_action_updated_date', 'community_board', 'borough',
                       'x_coordinate_state_plane', 'y_coordinate_state_plane',
                       'open_data_channel_type', 'park_facility_name', 'park_borough',
                       'latitude', 'longitude', 'location', 'intersection_street_1',
                       'intersection_street_2', 'bbl']]

In [ ]:
fig, ax = plt.subplots(figsize=(15,10))

sns.heatmap(heatmap.corr(), 
            annot=True, 
            ax=ax)

## 3.3 Identifying Null/NA Values

In [ ]:
print('Sum of nulls in column:')
flooding_311.isna().sum().sort_values(ascending=False)

In [ ]:
print('Sum of nulls in all columns:')
flooding_311.isna().sum().sum()

In [ ]:
print('Identifying nulls in column (True/False):')
flooding_311.isna().head()

In [ ]:
print('Identifying any null values in column (True/False):')
flooding_311.isna().any().sort_values(ascending=False)

In [ ]:
# return a boolean same-sized object indicating if any of the values are NA
flooding_311.isna().any().value_counts()

In [ ]:
# return descriptive statistics of boolean indicating if any of the values are NA
flooding_311.isna().any().describe()

In [ ]:
# calculating a percentage of the number of nulls to total number of records of each column
missing_data = (flooding_311.isna().sum() / len(flooding_311)) * 100

# creating a dataframe
missing_data = pd.DataFrame({'Missing Ratio (%)' :missing_data}) 
missing_data.sort_values(by='Missing Ratio (%)', 
                         ascending=False, 
                         inplace=True)

missing_data.head(len(missing_data))

## 3.4 Inspecting Items In Each Column

In [ ]:
len(flooding_311.columns)

In [ ]:
flooding_311.iloc[:,:15].head()

In [ ]:
flooding_311.iloc[:,15:30].head()

In [ ]:
flooding_311.iloc[:,30:].head()

In [ ]:
print('Returning a dataframe containing counts and normalized counts of unique rows in each column (sorted desc).',
     '\n' + '-' * 60, '\n')

for col in flooding_311.columns:
    series_1 = flooding_311[col].value_counts().head()
    series_2 = flooding_311[col].value_counts(normalize=True).head()
    series_2 = series_2.rename(str(col) +  ' (normalized)')
    value_counts = pd.concat([series_1, series_2], axis=1)
    
    print(value_counts, '\n' \
         'Column Name:', col + ',', 'dtype:', flooding_311[col].dtype, '\n')