In [20]:
# importing libraries
import pandas as pd
import numpy as np
from sodapy import Socrata
import os

In [21]:
socrata_domain = 'data.cityofnewyork.us'
socrata_dataset_identifier = 'erm2-nwe9'

# If you choose to use a token, run the following command on the terminal (or add it to your .bashrc)
# $ export SODAPY_APPTOKEN=<token>
socrata_token = os.environ.get("SODAPY_APPTOKEN")

In [22]:
client = Socrata(socrata_domain, socrata_token)

In [23]:
metadata = client.get_metadata(socrata_dataset_identifier)
[x['name'] for x in metadata['columns']]

['Unique Key',
 'Created Date',
 'Closed Date',
 'Agency',
 'Agency Name',
 'Complaint Type',
 'Descriptor',
 'Location Type',
 'Incident Zip',
 'Incident Address',
 'Street Name',
 'Cross Street 1',
 'Cross Street 2',
 'Intersection Street 1',
 'Intersection Street 2',
 'Address Type',
 'City',
 'Landmark',
 'Facility Type',
 'Status',
 'Due Date',
 'Resolution Description',
 'Resolution Action Updated Date',
 'Community Board',
 'BBL',
 'Borough',
 'X Coordinate (State Plane)',
 'Y Coordinate (State Plane)',
 'Open Data Channel Type',
 'Park Facility Name',
 'Park Borough',
 'Vehicle Type',
 'Taxi Company Borough',
 'Taxi Pick Up Location',
 'Bridge Highway Name',
 'Bridge Highway Direction',
 'Road Ramp',
 'Bridge Highway Segment',
 'Latitude',
 'Longitude',
 'Location',
 'Zip Codes',
 'Community Districts',
 'Borough Boundaries',
 'City Council Districts',
 'Police Precincts']

In [24]:
meta_amount = [x for x in metadata['columns'] if x['name'] == 'Complaint Type'][0]
meta_amount

{'id': 354922035,
 'name': 'Complaint Type',
 'dataTypeName': 'text',
 'description': 'This is the first level of a hierarchy identifying the topic of the incident or condition. Complaint Type may have a corresponding Descriptor (below) or may stand alone.',
 'fieldName': 'complaint_type',
 'position': 6,
 'renderTypeName': 'text',
 'tableColumnId': 1567792,
 'width': 268,
 'cachedContents': {'largest': 'ZTESTINT',
  'non_null': '25638802',
  'null': '0',
  'top': [{'item': 'Noise - Residential', 'count': '2224966'},
   {'item': 'HEAT/HOT WATER', 'count': '1406387'},
   {'item': 'Illegal Parking', 'count': '1116420'},
   {'item': 'Blocked Driveway', 'count': '1040777'},
   {'item': 'Street Condition', 'count': '1018671'},
   {'item': 'Street Light Condition', 'count': '981268'},
   {'item': 'HEATING', 'count': '887869'},
   {'item': 'PLUMBING', 'count': '744641'},
   {'item': 'Water System', 'count': '698926'},
   {'item': 'Noise - Street/Sidewalk', 'count': '680832'},
   {'item': 'Noise', 'count': '577251'},
   {'item': 'General Construction/Plumbing', 'count': '534014'},
   {'item': 'UNSANITARY CONDITION', 'count': '507321'},
   {'item': 'GENERAL CONSTRUCTION', 'count': '500863'},
   {'item': 'Traffic Signal Condition', 'count': '467487'},
   {'item': 'Noise - Commercial', 'count': '393716'},
   {'item': 'Sewer', 'count': '386544'},
   {'item': 'PAINT/PLASTER', 'count': '375180'},
   {'item': 'Dirty Conditions', 'count': '375055'},
   {'item': 'Damaged Tree', 'count': '363840'}],
  'smallest': '../../../../../../../../../...',
  'not_null': '21933957',
  'cardinality': '499'},
 'format': {'displayStyle': 'plain', 'align': 'left'}}

In [25]:
[x['fieldName'] for x in metadata['columns']]

['unique_key',
 'created_date',
 'closed_date',
 'agency',
 'agency_name',
 'complaint_type',
 'descriptor',
 'location_type',
 'incident_zip',
 'incident_address',
 'street_name',
 'cross_street_1',
 'cross_street_2',
 'intersection_street_1',
 'intersection_street_2',
 'address_type',
 'city',
 'landmark',
 'facility_type',
 'status',
 'due_date',
 'resolution_description',
 'resolution_action_updated_date',
 'community_board',
 'bbl',
 'borough',
 'x_coordinate_state_plane',
 'y_coordinate_state_plane',
 'open_data_channel_type',
 'park_facility_name',
 'park_borough',
 'vehicle_type',
 'taxi_company_borough',
 'taxi_pick_up_location',
 'bridge_highway_name',
 'bridge_highway_direction',
 'road_ramp',
 'bridge_highway_segment',
 'latitude',
 'longitude',
 'location',
 ':@computed_region_efsh_h5xi',
 ':@computed_region_f5dn_yrer',
 ':@computed_region_yeji_bk3q',
 ':@computed_region_92fq_4b7q',
 ':@computed_region_sbqj_enih']

In [26]:
# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("data.cityofnewyork.us", socrata_token, timeout=1000)

query = """
SELECT 
    complaint_type, count(complaint_type)
GROUP BY 
    complaint_type
ORDER BY 
    count(complaint_type) DESC
LIMIT 
    1000000
"""

# Returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("erm2-nwe9", 
                     query=query)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)

print(results_df.shape)
results_df.head(10)

(499, 2)

            complaint_type count_complaint_type
0      Noise - Residential              2224966
1           HEAT/HOT WATER              1406387
2          Illegal Parking              1116420
3         Blocked Driveway              1040777
4         Street Condition              1018671
5   Street Light Condition               981268
6                  HEATING               887869
7                 PLUMBING               744641
8             Water System               698926
9  Noise - Street/Sidewalk               680832

In [27]:
results_df.shape

(499, 2)

In [28]:
# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("data.cityofnewyork.us", socrata_token, timeout=1000)

query = """
SELECT 
    descriptor, count(descriptor)
WHERE 
    LOWER(descriptor) LIKE '%flood%'
GROUP BY 
    descriptor
ORDER BY 
    count(descriptor) DESC
LIMIT 
    1000000
"""

# Returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("erm2-nwe9", 
                     query=query)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)

print(results_df.shape)
results_df

(13, 2)

                                          descriptor count_descriptor
0   Catch Basin Clogged/Flooding (Use Comments) (SC)            90644
1                               Street Flooding (SJ)            27906
2                               Flood Light Lamp Out             5954
3                                 Flooding on Street             3175
4                              Highway Flooding (SH)             2839
5                           Flood Light Lamp Cycling             2510
6                                Ready NY - Flooding              271
7                        Flood Light Lamp Dayburning              205
8                           Flood Light Lamp Missing              190
9                               Flood Light Lamp Dim              177
10                     RAIN GARDEN FLOODING (SRGFLD)               85
11                               Flooding on Highway               76
12                                           Flooded               48

In [29]:
# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("data.cityofnewyork.us", socrata_token, timeout=1000)

query = """
SELECT 
    *
WHERE 
    LOWER(descriptor) LIKE '%flood%'
LIMIT 
    1000000
"""

# Returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("erm2-nwe9", 
                     query=query)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)

print(results_df.shape)
results_df.head()

(134080, 38)

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,cross_street_1,cross_street_2,intersection_street_1,...,location_type,incident_address,street_name,landmark,bbl,due_date,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment
0,49353103,2019-06-13T14:55:00.000,2019-07-30T08:08:03.000,DEP,Department of Environmental Protection,Sewer Maintenance,Flooding on Street,EAST 14 STREET,1 AVENUE,EAST 14 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20016014,2011-03-11T11:36:00.000,2011-03-22T11:15:00.000,DEP,Department of Environmental Protection,Sewer,Catch Basin Clogged/Flooding (Use Comments) (SC),FRESH MEADOW LANE LA,BOOTH MEMORIAL AVE,FRESH MEADOW LANE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20016017,2011-03-11T10:52:00.000,2011-03-15T06:00:00.000,DEP,Department of Environmental Protection,Sewer,Catch Basin Clogged/Flooding (Use Comments) (SC),DELANCEY ST,MANGIN ST,DELANCEY STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,49353099,2020-06-29T19:16:14.000,NaN,DEP,Department of Environmental Protection,Sewer Maintenance,Flooding on Street,18 AVENUE,19 AVENUE,18 AVENUE,...,Street,1887 54 STREET,54 STREET,54 STREET,3054800044,NaN,NaN,NaN,NaN,NaN
4,45989680,2020-04-12T14:14:00.000,2020-04-13T08:10:00.000,DEP,Department of Environmental Protection,Sewer,Street Flooding (SJ),BEMENT AVE,N BURGHER AVE,NaN,...,NaN,204 MORRISON AVENUE,MORRISON AVENUE,NaN,5003000147,NaN,NaN,NaN,NaN,NaN

In [30]:
results_df['descriptor'].value_counts()

Catch Basin Clogged/Flooding (Use Comments) (SC)    90644
Street Flooding (SJ)                                27906
Flood Light Lamp Out                                 5954
Flooding on Street                                   3175
Highway Flooding (SH)                                2839
Flood Light Lamp Cycling                             2510
Ready NY - Flooding                                   271
Flood Light Lamp Dayburning                           205
Flood Light Lamp Missing                              190
Flood Light Lamp Dim                                  177
RAIN GARDEN FLOODING (SRGFLD)                          85
Flooding on Highway                                    76
Flooded                                                48
Name: descriptor, dtype: int64

In [31]:
results_df = results_df[results_df['descriptor'] == 'Street Flooding (SJ)']

In [32]:
results_df['descriptor'].value_counts()

Street Flooding (SJ)    27906
Name: descriptor, dtype: int64

In [33]:
results_df['complaint_type'].value_counts()

Sewer    27906
Name: complaint_type, dtype: int64

In [34]:
results_df.shape

(27906, 38)

In [35]:
# writing output file as a csv
results_df.to_csv('../data-raw/raw-street-flooding-data.csv', index=False)

# listing items in data folder
%ls ../data-raw/

raw-street-flooding-data.csv  streets_clipped.json

# Briefly reviewing what descriptors are in the complaint_type='Sewer'

In [36]:
# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("data.cityofnewyork.us", socrata_token, timeout=1000)

# Example authenticated client (needed for non-public datasets):
# client = Socrata(data.cityofnewyork.us,
#                  MyAppToken,
#                  userame="user@example.com",
#                  password="AFakePassword")

query = """
SELECT 
    descriptor, count(descriptor)
WHERE 
    complaint_type='Sewer'
GROUP BY 
    descriptor
ORDER BY 
    count(descriptor) DESC
"""

# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("erm2-nwe9", 
                     query=query)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)

print(results_df.shape)
results_df.head(len(results_df))

(27, 2)

                                           descriptor count_descriptor
0                    Sewer Backup (Use Comments) (SA)           149659
1    Catch Basin Clogged/Flooding (Use Comments) (SC)            90644
2             Catch Basin Sunken/Damaged/Raised (SC1)            28718
3                                Street Flooding (SJ)            27906
4              Manhole Cover Broken/Making Noise (SB)            19777
5             Manhole Cover Missing (Emergency) (SA3)            17563
6                                    Sewer Odor (SA2)            15452
7                  Defective/Missing Curb Piece (SC4)             8517
8               Manhole Overflow (Use Comments) (SA1)             6875
9                            Catch Basin Search (SC2)             4153
10                  Catch Basin Grating Missing (SA4)             3767
11                Manhole Sunken/Damaged/Raised (SB1)             3430
12                              Highway Flooding (SH)             2839
13                Culvert Blocked/Needs Cleaning (SE)             2257
14           Other Sewer Problem (Use Comments) (SZZ)             1335
15                                  Sewer Break (SBR)             1036
16                    Plate Noisy/Sunken/Raised (SB5)              874
17            Plate Missing/Moved-Exposing Hole (SB4)              645
18                        RAIN GARDEN DEBRIS (SRGDBR)              386
19                   Street Cave-In / Depression (SG)              302
20                                      Trench (SZZ1)              192
21                      RAIN GARDEN FLOODING (SRGFLD)               85
22                   DAMAGE STRUCTURE/RAILING (SRGDM)               56
23       Street Cave-In *Dep Internal Use Only* (SG1)               31
24  Recurring after SOAP *FOR DEP INTERNAL USE ONL...               29
25  Catch Basin Connection Broken *Dep Internal Us...               15
26  SOAP segment *FOR DEP INTERNAL USE ONLY* (SOAP...                1